### ISSUE TITLE
build: bump Astropy to support v6+

### ISSUE THREAD

**Issue by nstarman** [ilikecubesnstuff/pidgey#9]
https://github.com/ilikecubesnstuff/pidgey/blob/4054fb8dded3de302ffc454819229bc03c2803fe/pyproject.toml#L11C5-L11C21

— openjournals/joss-reviews#7009

**Comment by ilikecubesnstuff** [comment]
My automated tests appear to be suffering from adrn/gala#376, but you are correct in pointing out that this package should not require Astropy v5 only. Thank you!
